<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Ardalis.GuardClauses" Version="5.0.0" />
    <PackageVersion Include="Fluentify" Version="3.0.0" />
    <PackageVersion Include="Graphify" Version="1.0.0-rc.18" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="5.6.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="[5.0.0,5.1.0)" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="[5.0.0,5.1.0)" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="[5.0.0,5.1.0)" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.3" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.10" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="8.0.0" />
    <PackageVersion Include="Monify" Version="1.5.1" />
    <PackageVersion Include="MooVC" Version="9.3.0-beta.36" />
    <PackageVersion Include="MooVC.Modelling" Version="9.3.0-beta.36" />
    <PackageVersion Include="MooVC.Syntax" Version="9.3.0-beta.36" />
    <PackageVersion Include="MooVC.Syntax.CSharp" Version="9.3.0-beta.36" />
    <PackageVersion Include="NSubstitute" Version="6.0.0" />
    <PackageVersion Include="protobuf-net" Version="3.2.56" />
    <PackageVersion Include="Serilog" Version="4.4.0" />
    <PackageVersion Include="SimpleInjector" Version="5.6.0" />
    <PackageVersion Include="SimpleInjector.Integration.GenericHost" Version="5.5.0" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.30.0.144632" />
    <PackageVersion Include="StyleCop.Analyzers" Version="1.2.0-beta.556" />
    <PackageVersion Include="System.Collections.Immutable" Version="10.0.10" />
    <PackageVersion Include="System.Text.Json" Version="10.0.10" />
    <PackageVersion Include="TUnit" Version="1.61.38" />
    <PackageVersion Include="Valuify" Version="1.9.0" />
  </ItemGroup>
</Project>