<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <GetTargetPathDependsOn>$(GetTargetPathDependsOn);GetDependencyTargetPaths</GetTargetPathDependsOn>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <NoPackageAnalysis>true</NoPackageAnalysis>
    <NoWarn>$(NoWarn);NU1608</NoWarn>
    <IsRoslynProject>true</IsRoslynProject>
    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);PackAnalyzerDependencies</TargetsForTfmSpecificContentInPackage>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Ardalis.GuardClauses" GeneratePathProperty="true" PrivateAssets="all" />
    <PackageReference Include="MooVC" GeneratePathProperty="true" PrivateAssets="all" />
    <PackageReference Include="MooVC.Modelling" GeneratePathProperty="true" PrivateAssets="all" />
    <PackageReference Include="MooVC.Syntax" GeneratePathProperty="true" PrivateAssets="all" />
    <PackageReference Include="MooVC.Syntax.CSharp" GeneratePathProperty="true" PrivateAssets="all" />
    <PackageReference Include="System.Collections.Immutable" GeneratePathProperty="true" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Mu.Modelling\Mu.Modelling.csproj" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Domain\ComponentIdentifierHasImplicitConversionVisitor.Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ComponentIdentifierHasImplicitConversionVisitor.Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Domain\IdentityAttributeAnalyzer.Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>IdentityAttributeAnalyzer.Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Domain\UnitAttributeAnalyzer.Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>UnitAttributeAnalyzer.Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Domain\ComponentIdentifierHasImplicitConversionVisitor.Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ComponentIdentifierHasImplicitConversionVisitor.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Domain\IdentityAttributeAnalyzer.Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>IdentityAttributeAnalyzer.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Domain\UnitAttributeAnalyzer.Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>UnitAttributeAnalyzer.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="Microsoft.CodeAnalysis.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <Target Name="GetDependencyTargetPaths" Condition="'$(IncludeAnalyzerDependencies)' == 'true'" DependsOnTargets="ResolveReferences">
    <ItemGroup>
      <TargetPathWithTargetPlatformMoniker Include="@(ReferenceCopyLocalPaths)" Condition="'%(ReferenceCopyLocalPaths.Extension)' == '.dll' AND '%(ReferenceCopyLocalPaths.Filename)' != '$(AssemblyName)' AND !$([System.String]::Copy('%(ReferenceCopyLocalPaths.Filename)').StartsWith('Microsoft.CodeAnalysis'))" IncludeRuntimeDependency="false" />
    </ItemGroup>
  </Target>
  <Target Name="PackAnalyzerDependencies" DependsOnTargets="ResolveReferences">
    <ItemGroup>
      <_AnalyzerDependency Include="@(ReferenceCopyLocalPaths)" Condition="'%(ReferenceCopyLocalPaths.Extension)' == '.dll' AND '%(ReferenceCopyLocalPaths.Filename)' != '$(AssemblyName)' AND !$([System.String]::Copy('%(ReferenceCopyLocalPaths.Filename)').StartsWith('Microsoft.CodeAnalysis'))" />
      <TfmSpecificPackageFile Include="$(OutputPath)\$(AssemblyName).pdb" PackagePath="analyzers/dotnet/cs" />
      <TfmSpecificPackageFile Include="@(_AnalyzerDependency)" PackagePath="analyzers/dotnet/cs" />
    </ItemGroup>
  </Target>
</Project>