<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <GetTargetPathDependsOn>$(GetTargetPathDependsOn);GetDependencyTargetPaths</GetTargetPathDependsOn>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <NoPackageAnalysis>true</NoPackageAnalysis>
    <NoWarn>$(NoWarn);NU1608</NoWarn>
    <IsRoslynProject>true</IsRoslynProject>
    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);PackAnalyzerDependencies</TargetsForTfmSpecificContentInPackage>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Ardalis.GuardClauses" GeneratePathProperty="true" PrivateAssets="all" />
    <PackageReference Include="MooVC" GeneratePathProperty="true" PrivateAssets="all" />
    <PackageReference Include="MooVC.Modelling" GeneratePathProperty="true" PrivateAssets="all" />
    <PackageReference Include="MooVC.Syntax" GeneratePathProperty="true" PrivateAssets="all" />
    <PackageReference Include="MooVC.Syntax.CSharp" GeneratePathProperty="true" PrivateAssets="all" />
    <PackageReference Include="System.Collections.Immutable" GeneratePathProperty="true" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Mu.Modelling\Mu.Modelling.csproj" PrivateAssets="all" />
  </ItemGroup>
  <Target Name="GetDependencyTargetPaths">
    <MSBuild Projects="@(ProjectReference)" Targets="GetTargetPath" Properties="Configuration=$(Configuration);TargetFramework=$(TargetFramework)">
      <Output TaskParameter="TargetOutputs" ItemName="_ProjectReferenceTargetPaths" />
    </MSBuild>
    <ItemGroup>
      <TargetPathWithTargetPlatformMoniker Include="$(PkgArdalis_GuardClauses)\lib\netstandard2.0\Ardalis.GuardClauses.dll" IncludeRuntimeDependency="false" />
      <TargetPathWithTargetPlatformMoniker Include="$(PkgMooVC)\lib\netstandard2.0\MooVC.dll" IncludeRuntimeDependency="false" />
      <TargetPathWithTargetPlatformMoniker Include="$(PkgMooVC_Modelling)\lib\netstandard2.0\MooVC.Modelling.dll" IncludeRuntimeDependency="false" />
      <TargetPathWithTargetPlatformMoniker Include="$(PkgMooVC_Syntax)\lib\netstandard2.0\MooVC.Syntax.dll" IncludeRuntimeDependency="false" />
      <TargetPathWithTargetPlatformMoniker Include="$(PkgMooVC_Syntax_CSharp)\lib\netstandard2.0\MooVC.Syntax.CSharp.dll" IncludeRuntimeDependency="false" />
      <TargetPathWithTargetPlatformMoniker Include="$(PkgSystem_Collections_Immutable)\lib\netstandard2.0\System.Collections.Immutable.dll" IncludeRuntimeDependency="false" />
      <TargetPathWithTargetPlatformMoniker Include="@(_ProjectReferenceTargetPaths)" IncludeRuntimeDependency="false" />
    </ItemGroup>
  </Target>
  <Target Name="PackAnalyzerDependencies" DependsOnTargets="ResolveReferences">
    <ItemGroup>
      <_AnalyzerDependency Include="@(ReferenceCopyLocalPaths)" Condition="'%(ReferenceCopyLocalPaths.Extension)' == '.dll' AND '%(ReferenceCopyLocalPaths.Filename)' != '$(AssemblyName)' AND !$([System.String]::Copy('%(ReferenceCopyLocalPaths.Filename)').StartsWith('Microsoft.CodeAnalysis'))" />
      <TfmSpecificPackageFile Include="@(_AnalyzerDependency)" PackagePath="analyzers/dotnet/cs" />
    </ItemGroup>
  </Target>
</Project>