namespace Muify.Service
{
    internal sealed class CreationalAttributeStrategy
        : MutationalAttributeStrategy
    {
        /// <summary>
        /// The hint name used for the code generated by the generator.
        /// </summary>
        internal const string Hint = "CreationalAttribute.g.cs";

        /// <summary>
        /// The name of the attribute (without the suffix).
        /// </summary>
        internal const string Name = "Creational";

        public CreationalAttributeStrategy()
            : base(Hint, Name)
        {
        }
    }
}