namespace Muify.Service
{
    using System;
    using System.Text;
    using Microsoft.CodeAnalysis;
    using Microsoft.CodeAnalysis.Text;
    using MooVC.Syntax;
    using MooVC.Syntax.CSharp;
    using Attribute = System.Attribute;

    [Generator(LanguageNames.CSharp)]
    public sealed class NonMutationalGenerator
        : IIncrementalGenerator
    {
        /// <summary>
        /// The hint name used for the code generated by the generator.
        /// </summary>
        internal const string Hint = "NonMutationalAttribute.g.cs";

        /// <summary>
        /// The name of the attribute (without the suffix).
        /// </summary>
        internal const string Name = "NonMutational";

        /// <inheritdoc/>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(Generate);
        }

        private static void Generate(IncrementalGeneratorPostInitializationContext context)
        {
            var content = Builder
                .New<Definition>()
                .From(typeof(NonMutationalGenerator))
                .For<Class>(@class => @class
                    .AttributedWith(attribute => attribute
                        .Named(typeof(AttributeUsageAttribute))
                        .WithArguments(
                            (Name: string.Empty, Value: "global::System.AttributeTargets.Class"),
                            (Name: nameof(AttributeUsageAttribute.AllowMultiple), Value: "false"),
                            (Name: nameof(AttributeUsageAttribute.Inherited), Value: "false")))
                    .AttributedWith(attribute => attribute
                        .Named((Name: "EmbeddedAttribute", Qualifier: "Microsoft.CodeAnalysis")))
                    .DerivesFrom(typeof(Attribute))
                    .Named($"{Name}Attribute")
                    .WithScope(Scopes.Internal))
                .ToSnippet(Configuration.Options);

            context.AddSource(Hint, SourceText.From(content, Encoding.UTF8));
        }
    }
}