namespace Muify.Service
{
    using System;
    using MooVC.Syntax;
    using MooVC.Syntax.CSharp;
    using Muify.Syntax.CSharp;
    using Attribute = System.Attribute;

    internal sealed class NonMutationalStrategy
        : AttributeStrategy
    {
        /// <summary>
        /// The hint name used for the code generated by the generator.
        /// </summary>
        internal const string Hint = "Muify.Service.NonMutationalAttribute.g.cs";

        /// <summary>
        /// The name of the attribute (without the suffix).
        /// </summary>
        internal const string Name = "NonMutational";

        public NonMutationalStrategy()
            : base(Hint)
        {
        }

        protected override Snippet GetContent()
        {
            Symbol targets = typeof(AttributeTargets);

            return Builder
                .New<Definition>()
                .From(typeof(NonMutationalStrategy))
                .For<Class>(@class => @class
                    .AddEmbeddedAttribute()
                    .AttributedWith(usage => usage
                        .Named(typeof(AttributeUsageAttribute))
                        .WithArguments(
                            (Name: string.Empty, Value: $"{targets.ToSnippet(Configuration.Options)}.Class"),
                            (Name: nameof(AttributeUsageAttribute.AllowMultiple), Value: "false"),
                            (Name: nameof(AttributeUsageAttribute.Inherited), Value: "false")))
                    .DerivesFrom(typeof(Attribute))
                    .Named($"{Name}Attribute"))
                .ToSnippet(Configuration.Options);
        }
    }
}