namespace Muify.Service
{
    using Microsoft.CodeAnalysis;

    [Generator(LanguageNames.CSharp)]
    public sealed class TransitionalAttributeGenerator
        : MutationalAttributeGenerator
    {
        /// <summary>
        /// The hint name used for the code generated by the generator.
        /// </summary>
        internal const string Hint = "TransitionalAttribute.g.cs";

        /// <summary>
        /// The name of the attribute (without the suffix).
        /// </summary>
        internal const string Name = "Transitional";

        public TransitionalAttributeGenerator()
            : base(Hint, Name)
        {
        }
    }
}