//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mu.Persistence {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InMemoryStream_Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InMemoryStream_Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mu.Persistence.InMemoryStream.Resources", typeof(InMemoryStream_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The facts to be appended to the stream for `{0}` at revision `{1}` must be provided..
        /// </summary>
        internal static string AppendFactsRequired {
            get {
                return ResourceManager.GetString("AppendFactsRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The stream for identity `{0}` has not been initiated..
        /// </summary>
        internal static string AppendIdentityInitiatedRequired {
            get {
                return ResourceManager.GetString("AppendIdentityInitiatedRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The identity of the stream to which the facts are to be appended must be provided..
        /// </summary>
        internal static string AppendIdentityRequired {
            get {
                return ResourceManager.GetString("AppendIdentityRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The stream for identity `{0}` is at revision `{1}`, not `{2}`..
        /// </summary>
        internal static string AppendRevisionMatchRequired {
            get {
                return ResourceManager.GetString("AppendRevisionMatchRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The options for finding events in the stream must be provided..
        /// </summary>
        internal static string FindOptionsRequired {
            get {
                return ResourceManager.GetString("FindOptionsRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The facts to initialize the stream for `{0}` must be provided..
        /// </summary>
        internal static string InitiateFactsRequired {
            get {
                return ResourceManager.GetString("InitiateFactsRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The identity of the stream to initiate for `{0}` must be provided..
        /// </summary>
        internal static string InitiateIdentityRequired {
            get {
                return ResourceManager.GetString("InitiateIdentityRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The stream for identity `{0}` has already been initiated..
        /// </summary>
        internal static string InitiateIdentityUninitiatedRequired {
            get {
                return ResourceManager.GetString("InitiateIdentityUninitiatedRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The semaphore used to synchronize access to the stream must be provided..
        /// </summary>
        internal static string SemaphoreRequired {
            get {
                return ResourceManager.GetString("SemaphoreRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The fact at index `{0}` for the stream `{1}` at revision `{2}` cannot be null..
        /// </summary>
        internal static string WriteFactRequired {
            get {
                return ResourceManager.GetString("WriteFactRequired", resourceCulture);
            }
        }
    }
}
