<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
    <LangVersion Condition="'$(TargetFramework)' == 'netstandard2.0'">7.3</LangVersion>
    <LangVersion Condition="'$(TargetFramework)' == 'net10.0'">latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Mu.Modelling.Testing</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Muify</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Muify.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Fluentify">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Monify">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MooVC.Modelling" />
    <PackageReference Include="MooVC.Syntax.CSharp" />
    <PackageReference Include="System.Text.Json" />
    <PackageReference Include="Valuify">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Model.Graph.Areas.Area.cs">
      <DependentUpon>Model.cs</DependentUpon>
    </Compile>
    <Compile Update="Model.Graph.Areas.Area.Components.Component.cs">
      <DependentUpon>Model.Graph.Areas.Area.cs</DependentUpon>
    </Compile>
    <Compile Update="Model.Graph.Areas.Area.Lists.List.cs">
      <DependentUpon>Model.Graph.Areas.Area.cs</DependentUpon>
    </Compile>
    <Compile Update="Model.Graph.Areas.Area.Units.Unit.cs">
      <DependentUpon>Model.Graph.Areas.Area.cs</DependentUpon>
    </Compile>
    <Compile Update="Model.Graph.Areas.Area.Units.Unit.Components.Component.cs">
      <DependentUpon>Model.Graph.Areas.Area.Units.Unit.cs</DependentUpon>
    </Compile>
    <Compile Update="Model.Graph.Areas.Area.Units.Unit.Features.Feature.cs">
      <DependentUpon>Model.Graph.Areas.Area.Units.Unit.cs</DependentUpon>
    </Compile>
    <Compile Update="Model.Graph.Areas.Area.Units.Unit.Lists.List.cs">
      <DependentUpon>Model.Graph.Areas.Area.Units.Unit.cs</DependentUpon>
    </Compile>
    <Compile Update="Model.Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Model.Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Model.Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Model.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>