<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="protobuf-net.Grpc.AspNetCore" />
    <ProjectReference Include="..\Mu.Composition\Mu.Composition.csproj" />
    <ProjectReference Include="..\Mu\Mu.csproj" />
  </ItemGroup>
</Project>