//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muify.Domain {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AggregateConstructorAnalyzer_Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AggregateConstructorAnalyzer_Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Muify.Domain.AggregateConstructorAnalyzer.Resources", typeof(AggregateConstructorAnalyzer_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Positional records deriving from Aggregate or annotated with Unit&lt;&gt; must satisfy the new() constraint. The type must be non-abstract and have a public parameterless constructor. If it has required members, that constructor must be annotated with SetsRequiredMembers..
        /// </summary>
        internal static string ConstructorConstraintDescription {
            get {
                return ResourceManager.GetString("ConstructorConstraintDescription", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Type `{0}` deriving from Aggregate or annotated with Unit&lt;&gt; must satisfy the new() constraint: it must be non-abstract and have a public parameterless constructor that satisfies any required members.
        /// </summary>
        internal static string ConstructorConstraintMessage {
            get {
                return ResourceManager.GetString("ConstructorConstraintMessage", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Aggregate Constructor Constraint Not Satisfied.
        /// </summary>
        internal static string ConstructorConstraintTitle {
            get {
                return ResourceManager.GetString("ConstructorConstraintTitle", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        internal static string DiagnosticCategory {
            get {
                return ResourceManager.GetString("DiagnosticCategory", resourceCulture);
            }
        }
    }
}