namespace Muify.Domain
{
    using System;
    using MooVC.Syntax;
    using MooVC.Syntax.CSharp;
    using Muify.Syntax.CSharp;
    using Attribute = System.Attribute;

    internal sealed class IdentityAttributeStrategy
        : AttributeStrategy
    {
        /// <summary>
        /// The hint name used for the code generated by the generator.
        /// </summary>
        internal const string Hint = "IdentityAttribute.g.cs";

        /// <summary>
        /// The name of the attribute (without the suffix).
        /// </summary>
        internal const string Name = "Identity";

        public IdentityAttributeStrategy()
            : base(Hint)
        {
        }

        protected override Snippet GetContent()
        {
            return Builder
                .New<Definition>()
                .From(typeof(IdentityAttributeStrategy))
                .For<Class>(@class => @class
                    .AddEmbeddedAttribute()
                    .AttributedWith(usage => usage
                        .Named(typeof(AttributeUsageAttribute))
                        .WithArguments(
                            (Name: string.Empty, Value: "global::System.AttributeTargets.Property"),
                            (Name: nameof(AttributeUsageAttribute.AllowMultiple), Value: "false"),
                            (Name: nameof(AttributeUsageAttribute.Inherited), Value: "false")))
                    .DerivesFrom(typeof(Attribute))
                    .Named($"{Name}Attribute"))
                .ToSnippet(Configuration.Options);
        }
    }
}