namespace Muify.Domain
{
    using System;
    using System.Text;
    using Microsoft.CodeAnalysis;
    using Microsoft.CodeAnalysis.Text;
    using MooVC.Syntax;
    using MooVC.Syntax.CSharp;
    using Attribute = System.Attribute;

    [Generator(LanguageNames.CSharp)]
    public sealed class IdentityAttributeGenerator
        : AttributeGenerator
    {
        /// <summary>
        /// The hint name used for the code generated by the generator.
        /// </summary>
        internal const string Hint = "IdentityAttribute.g.cs";

        /// <summary>
        /// The name of the attribute (without the suffix).
        /// </summary>
        internal const string Name = "Identity";

        /// <summary>
        /// The name of the type within the compilation that is used to determine whether the generator should run or not.
        /// </summary>
        internal const string Metadata = "Muify.Domain.IdentityAttribute";

        public IdentityAttributeGenerator()
            : base(Hint, Metadata)
        {
        }

        protected override Snippet GetContent()
        {
            return Builder
                .New<Definition>()
                .From(typeof(IdentityAttributeGenerator))
                .For<Class>(@class => @class
                    .AttributedWith(usage => usage
                        .Named(typeof(AttributeUsageAttribute))
                        .WithArguments(
                            (Name: string.Empty, Value: "global::System.AttributeTargets.Property"),
                            (Name: nameof(AttributeUsageAttribute.AllowMultiple), Value: "false"),
                            (Name: nameof(AttributeUsageAttribute.Inherited), Value: "false")))
                    .DerivesFrom(typeof(Attribute))
                    .Named($"{Name}Attribute"))
                .ToSnippet(Configuration.Options);
        }
    }
}