namespace Muify.Domain
{
    using System;
    using MooVC.Syntax;
    using MooVC.Syntax.CSharp;
    using Muify.Syntax.CSharp;
    using Attribute = System.Attribute;

    internal sealed class UnitAttributeStrategy
        : AttributeStrategy
    {
        /// <summary>
        /// The hint name used for the code generated by the generator.
        /// </summary>
        internal const string Hint = "Muify.Domain.UnitAttribute.g.cs";

        /// <summary>
        /// The name of the attribute (without the suffix).
        /// </summary>
        internal const string Name = "Unit";

        public UnitAttributeStrategy()
            : base(Hint)
        {
        }

        protected override Snippet GetContent()
        {
            Symbol targets = typeof(AttributeTargets);

            return Builder
                .New<Definition>()
                .From(typeof(UnitAttributeStrategy))
                .For<Class>(@class => @class
                    .AddEmbeddedAttribute()
                    .AttributedWith(usage => usage
                        .Named(typeof(AttributeUsageAttribute))
                        .WithArguments(
                            (Name: string.Empty, Value: $"{targets.ToSnippet(Configuration.Options)}.Class"),
                            (Name: nameof(AttributeUsageAttribute.AllowMultiple), Value: "false"),
                            (Name: nameof(AttributeUsageAttribute.Inherited), Value: "false")))
                    .DerivesFrom(typeof(Attribute))
                    .Named(declaration => declaration
                        .WithArguments(identity => identity
                            .Named("TIdentity")
                            .WithConstraints(@struct => @struct.WithNature(Natures.Struct)))
                        .Named($"{Name}Attribute")))
                .ToSnippet(Configuration.Options);
        }
    }
}