//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mu.Auditing {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InMemoryAuditor_Resources {

        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        internal InMemoryAuditor_Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mu.Auditing.InMemoryAuditor.Resources", typeof(InMemoryAuditor_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The message to audit must be provided..
        /// </summary>
        internal static string CaptureMessageRequired {
            get {
                return ResourceManager.GetString("CaptureMessageRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The audit outcome must be provided..
        /// </summary>
        internal static string CompleteOutcomeRequired {
            get {
                return ResourceManager.GetString("CompleteOutcomeRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The cause of the audit failure must be provided..
        /// </summary>
        internal static string FailCauseRequired {
            get {
                return ResourceManager.GetString("FailCauseRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No message has been captured for audit identity `{0}`..
        /// </summary>
        internal static string UpdateIdentityCapturedRequired {
            get {
                return ResourceManager.GetString("UpdateIdentityCapturedRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The audit for identity `{0}` has already completed or failed..
        /// </summary>
        internal static string UpdateIdentityPendingRequired {
            get {
                return ResourceManager.GetString("UpdateIdentityPendingRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The audit identity must be provided..
        /// </summary>
        internal static string UpdateIdentityRequired {
            get {
                return ResourceManager.GetString("UpdateIdentityRequired", resourceCulture);
            }
        }
    }
}