<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <ProjectReference Include="..\Mu.Modelling.Tests\Mu.Modelling.Tests.csproj" />
    <ProjectReference Include="..\Mu\Mu.csproj" Aliases="Framework" />
  </ItemGroup>
</Project>