<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Ardalis.GuardClauses" />
    <PackageReference Include="Fluentify" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="MooVC" />
    <PackageReference Include="protobuf-net.Grpc.AspNetCore" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="SimpleInjector.Integration.AspNetCore" />
  </ItemGroup>
</Project>