<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Ardalis.GuardClauses" />
    <PackageReference Include="Fluentify" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="MooVC" />
    <PackageReference Include="protobuf-net.Grpc.AspNetCore" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="SimpleInjector.Integration.AspNetCore" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Auditing\Composition\ContainerExtensions.Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ContainerExtensions.Resources.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Auditing\Composition\ContainerExtensions.Resources.resx">
      <LogicalName>Mu.Auditing.Composition.ContainerExtensions.Resources.resources</LogicalName>
      <WithCulture>false</WithCulture>
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ContainerExtensions.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <Compile Update="Auditing\InMemoryAuditor.Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>InMemoryAuditor.Resources.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Auditing\InMemoryAuditor.Resources.resx">
      <LogicalName>Mu.Auditing.InMemoryAuditor.Resources.resources</LogicalName>
      <WithCulture>false</WithCulture>
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>InMemoryAuditor.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <Compile Update="Communications\Mediation\Composition\ContainerExtensions.Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ContainerExtensions.Resources.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Communications\Mediation\Composition\ContainerExtensions.Resources.resx">
      <LogicalName>Mu.Communications.Mediation.Composition.ContainerExtensions.Resources.resources</LogicalName>
      <WithCulture>false</WithCulture>
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ContainerExtensions.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <Compile Update="Communications\Tracing\Scribe.Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Scribe.Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Persistence\Composition\ContainerExtensions.Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ContainerExtensions.Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Communications\Tracing\Scribe.Resources.resx">
      <LogicalName>Mu.Communications.Tracing.Scribe.Resources.resources</LogicalName>
      <WithCulture>false</WithCulture>
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Scribe.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Communications\PubSub\InMemoryPublisher.Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>InMemoryPublisher.Resources.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Communications\PubSub\InMemoryPublisher.Resources.resx">
      <LogicalName>Mu.Communications.PubSub.InMemoryPublisher.Resources.resources</LogicalName>
      <WithCulture>false</WithCulture>
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>InMemoryPublisher.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <Compile Update="Communications\PubSub\Policy.Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Policy.Resources.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Communications\PubSub\Policy.Resources.resx">
      <LogicalName>Mu.Communications.PubSub.Policy.Resources.resources</LogicalName>
      <WithCulture>false</WithCulture>
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Policy.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <Compile Update="Communications\PubSub\ReflectionPolicyDirectory.Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ReflectionPolicyDirectory.Resources.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Communications\PubSub\ReflectionPolicyDirectory.Resources.resx">
      <LogicalName>Mu.Communications.PubSub.ReflectionPolicyDirectory.Resources.resources</LogicalName>
      <WithCulture>false</WithCulture>
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ReflectionPolicyDirectory.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <Compile Update="Communications\Tracing\CallContextExtensions.Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CallContextExtensions.Resources.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Communications\Tracing\CallContextExtensions.Resources.resx">
      <LogicalName>Mu.Communications.Tracing.CallContextExtensions.Resources.resources</LogicalName>
      <WithCulture>false</WithCulture>
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>CallContextExtensions.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <Compile Update="Composition\IApplicationBuilderExtensions.Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>IApplicationBuilderExtensions.Resources.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Composition\IApplicationBuilderExtensions.Resources.resx">
      <LogicalName>Mu.Composition.IApplicationBuilderExtensions.Resources.resources</LogicalName>
      <WithCulture>false</WithCulture>
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>IApplicationBuilderExtensions.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <Compile Update="Composition\IHostApplicationBuilderExtensions.Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>IHostApplicationBuilderExtensions.Resources.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Composition\IHostApplicationBuilderExtensions.Resources.resx">
      <LogicalName>Mu.Composition.IHostApplicationBuilderExtensions.Resources.resources</LogicalName>
      <WithCulture>false</WithCulture>
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>IHostApplicationBuilderExtensions.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <Compile Update="Composition\IServiceCollectionExtensions.Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>IServiceCollectionExtensions.Resources.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Composition\IServiceCollectionExtensions.Resources.resx">
      <LogicalName>Mu.Composition.IServiceCollectionExtensions.Resources.resources</LogicalName>
      <WithCulture>false</WithCulture>
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>IServiceCollectionExtensions.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <Compile Update="Composition\WebApplicationBuilderExtensions.Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>WebApplicationBuilderExtensions.Resources.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Composition\WebApplicationBuilderExtensions.Resources.resx">
      <LogicalName>Mu.Composition.WebApplicationBuilderExtensions.Resources.resources</LogicalName>
      <WithCulture>false</WithCulture>
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>WebApplicationBuilderExtensions.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <Compile Update="Modelling\Representation.Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Representation.Resources.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Modelling\Representation.Resources.resx">
      <LogicalName>Mu.Modelling.Representation.Resources.resources</LogicalName>
      <WithCulture>false</WithCulture>
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Representation.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <Compile Update="Modelling\Services\ReflectionTransform.Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ReflectionTransform.Resources.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Modelling\Services\ReflectionTransform.Resources.resx">
      <LogicalName>Mu.Modelling.Services.ReflectionTransform.Resources.resources</LogicalName>
      <WithCulture>false</WithCulture>
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ReflectionTransform.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <Compile Update="Modelling\Services\Transform.Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Transform.Resources.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Modelling\Services\Transform.Resources.resx">
      <LogicalName>Mu.Modelling.Services.Transform.Resources.resources</LogicalName>
      <WithCulture>false</WithCulture>
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Transform.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <Compile Update="Persistence\InMemoryStream.Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>InMemoryStream.Resources.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Persistence\Composition\ContainerExtensions.Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ContainerExtensions.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Persistence\InMemoryStream.Resources.resx">
      <LogicalName>Mu.Persistence.InMemoryStream.Resources.resources</LogicalName>
      <WithCulture>false</WithCulture>
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>InMemoryStream.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <Compile Update="Range.Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Range.Resources.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Range.Resources.resx">
      <LogicalName>Mu.Range.Resources.resources</LogicalName>
      <WithCulture>false</WithCulture>
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Range.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <Compile Update="Result.Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Result.Resources.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Result.Resources.resx">
      <LogicalName>Mu.Result.Resources.resources</LogicalName>
      <WithCulture>false</WithCulture>
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Result.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Communications\Tracing\Scope.Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Scope.Resources.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Communications\Tracing\Scope.Resources.resx">
      <LogicalName>Mu.Communications.Tracing.Scope.Resources.resources</LogicalName>
      <WithCulture>false</WithCulture>
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Scope.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Modelling\Integrity\Specification.Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Specification.Resources.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Modelling\Integrity\Specification.Resources.resx">
      <LogicalName>Mu.Modelling.Integrity.Specification.Resources.resources</LogicalName>
      <WithCulture>false</WithCulture>
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Specification.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Contract.Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Contract.Resources.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Contract.Resources.resx">
      <LogicalName>Mu.Contract.Resources.resources</LogicalName>
      <WithCulture>false</WithCulture>
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Contract.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Serialization\RuntimeTypeModelExtensions.Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>RuntimeTypeModelExtensions.Resources.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Serialization\RuntimeTypeModelExtensions.Resources.resx">
      <LogicalName>Mu.Serialization.RuntimeTypeModelExtensions.Resources.resources</LogicalName>
      <WithCulture>false</WithCulture>
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>RuntimeTypeModelExtensions.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Modelling\State\AggregateExtensions.Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AggregateExtensions.Resources.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Modelling\State\AggregateExtensions.Resources.resx">
      <LogicalName>Mu.Modelling.State.AggregateExtensions.Resources.resources</LogicalName>
      <WithCulture>false</WithCulture>
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>AggregateExtensions.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Modelling\Integrity\Invariant.Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Invariant.Resources.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Modelling\Integrity\Invariant.Resources.resx">
      <LogicalName>Mu.Modelling.Integrity.Invariant.Resources.resources</LogicalName>
      <WithCulture>false</WithCulture>
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Invariant.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Persistence\WriteStore.Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>WriteStore.Resources.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Persistence\WriteStore.Resources.resx">
      <LogicalName>Mu.Persistence.WriteStore.Resources.resources</LogicalName>
      <WithCulture>false</WithCulture>
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>WriteStore.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Communications\Messaging\Intent.Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Intent.Resources.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Communications\Messaging\Intent.Resources.resx">
      <LogicalName>Mu.Communications.Messaging.Intent.Resources.resources</LogicalName>
      <WithCulture>false</WithCulture>
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Intent.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Failure.Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Failure.Resources.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Failure.Resources.resx">
      <LogicalName>Mu.Failure.Resources.resources</LogicalName>
      <WithCulture>false</WithCulture>
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Failure.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Communications\Messaging\Event.Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Event.Resources.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Communications\Messaging\Event.Resources.resx">
      <LogicalName>Mu.Communications.Messaging.Event.Resources.resources</LogicalName>
      <WithCulture>false</WithCulture>
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Event.Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>